FROM node:18-alpine as build-stage

WORKDIR /app
COPY package*.json .
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx:alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

ENTRYPOINT [ "nginx", "-c", "/etc/nginx/conf.d/default.conf", "-g", "daemon off;" ]
